// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleLibraryCore.Models
{
    public partial class Contact
    {
        public Contact()
        {
            Customers = new HashSet<Customer>();
        }

        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<Customer> Customers { get; set; }
    }
}