// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleLibraryCore.Models
{
    public partial class LanguageCode
    {
        public int LanguageId { get; set; }
        public string LanguageCodes { get; set; }
        public string ColumnDescription { get; set; }
    }
}