// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleLibraryCore.Models
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            PaymentTransactions = new HashSet<PaymentTransaction>();
        }

        public int PaymentTypeIdentifier { get; set; }
        public string PaymentDescription { get; set; }

        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
    }
}