// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleLibraryCore.Models
{
    public partial class PaymentTransaction
    {
        public int TransactionIdentifier { get; set; }
        public int? CustomerIdentifier { get; set; }
        public int? OrderId { get; set; }
        public int? PaymentTypeIdentifier { get; set; }
        public DateTime? PaymentDate { get; set; }
        public decimal? Amount { get; set; }

        public virtual PaymentType PaymentTypeIdentifierNavigation { get; set; }
    }
}