// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleLibraryCore.Models
{
    public partial class PersonTitle
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ColumnDescription { get; set; }
    }
}